### ISSUE TITLE
L2 loss being added once for each stage instead of once overall?

### ISSUE THREAD

**Issue by tnybny** [anibali/margipose#21]
The euclidean loss between ground truth and predicted coordinates is added once for each stage, but should be added only once, correct? Am I missing something?
https://github.com/anibali/margipose/blob/e96d59187dc17651ab184ca263f9a1a150cfa201/src/margipose/models/margipose_model.py#L244

**Comment by anibali** [comment]
Yes you are correct, that is a bug that I found a couple of months ago. In fact, the intention _is_ to calculate the euclidean loss at each stage, but using the coordinate predictions from those stages (rather than repeating the same calculation based on the final predictions). However, I found that fixing it did not really affect the results so I didn't push the fix to this repo.

**Comment by anibali** [comment]
Fixed in https://github.com/anibali/margipose/commit/604494922989b58a5f1fa5d2ecfbe7e062578dae.
