### ISSUE TITLE
Running into failure due to version incompatibility with matplotlib 3.x

### ISSUE THREAD

**Issue by jaesungj** [anibali/margipose#28]
File "/opt/conda/lib/python3.6/site-packages/margipose/utils.py", line 144, in plot_skeleton_on_axes3d
    ax.set_aspect('equal')
  File "/opt/conda/lib/python3.6/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 324, in set_aspect
    "Axes3D currently only supports the aspect argument "

NotImplementedError: Axes3D currently only supports the aspect argument 'auto'. You passed in 'equal'. 

Hello do you by any chance have plan to make changes so that utils.py becomes compatible with matplot lib 3.x?
https://github.com/matplotlib/matplotlib/issues/1077/

**Comment by anibali** [comment]
No, my understanding is that this functionality was removed in newer versions of Matplotlib and never replaced. If you want to use MargiPose in a project that depends on a newer version of Matplotlib, just avoid using the demo code or `plot_skeleton_on_axes3d` and everything should work OK. Otherwise, if you want to demo MargiPose, install it in its own environment with the older version of Matplotlib.
